INSERT INTO posts (titulo, img, descripcion, likes)
VALUES 
	('Torres del Paine, Chile',
	'https://media.istockphoto.com/id/117149827/es/foto/guanaco-de-torres-del-paine-xxxl.jpg?s=1024x1024&w=is&k=20&c=wD2K5MKbU5iybeOh7cSpidULIAfwwma0MDZ3YEYtQ7g=',
	'Guanaco en las Torres del Paine, Chile', 0),
	('Puerto Varas, Chile',
	'https://media.istockphoto.com/id/922671166/es/foto/ciudad-de-puerto-varas.jpg?s=1024x1024&w=is&k=20&c=40Az9ABFUFn4chweDjxY0N6nTMYJXb1zKJ8D1AH8Lpw=',
	'Ciudad de Puerto Varas y volcán Osorno', 0),
	('Atacama, Chile',
	'https://media.istockphoto.com/id/1406815792/es/foto/reflejo-del-lago-lejia-al-amanecer-cerca-de-los-volcanes-de-atacama-chile.jpg?s=1024x1024&w=is&k=20&c=hCn5kAho0trg56s-pHRLbhwIb_tOT6tKaECHl11gSaU=',
	'Reflejo del lago Lejia al amanecer, cerca de los volcanes de Atacama, Chile', 0),
	('Mina de Cobre, Chile',
	'https://media.istockphoto.com/id/1326466508/es/foto/mina-de-cobre-a-cielo-abierto.jpg?s=1024x1024&w=is&k=20&c=UnnUN5jOn6nE_kWKLcmasq8Qt__euScjhXCRDX30DgI=',
	'Mina de cobre a cielo abierto, Chile', 0),
	('Arica, Chile',
	'https://media.istockphoto.com/id/1027438214/es/foto/el-gran-nevados-de-payachatas-pomerape-y-parinacota-volcanes-izquierda-y-derecha.jpg?s=1024x1024&w=is&k=20&c=Hs3IlYu-Ge5t7ZL2WE0n_Nx4UiSYpXO_WkALnRWwlkU=',
	'El gran Nevados de Payachatas Pomerape, Parinacota volcanes, Núcleo Galáctico de la vía Láctea, laguna de Cotacotani aguas, Arica, Chile', 0),
	('Santiago, Chile',
	'https://media.istockphoto.com/id/1473127709/es/foto/vista-de-la-ciudad-de-santiago-de-chile-desde-el-cerro-san-crist%C3%B3bal.jpg?s=1024x1024&w=is&k=20&c=4v_cParlhDjel6gT1LFWFmSUOz0Jcg9ujX66bsSMxBg=',
	'Vista de la ciudad de Santiago de Chile, desde el cerro San Cristóbal', 0);